[project]
name = "boss-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "patchright>=1.55.2",
    "pyvirtualdisplay>=3.0",
    "redis>=5.0.0",
    "requests>=2.32.5",
    "retry>=0.9.2",
]
